services:
  - type: web
    name: flashcards-backend
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application